[project]
dependencies = []
description = "Add a short description here"
name = "lightglue-glomap"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["lightglue_glomap*"]

[tool.pixi.project]
channels = ["nvidia", "nvidia/label/cuda-11.8.0", "conda-forge", "pytorch"]
platforms = ["linux-64"]

[tool.pixi.system-requirements]
libc = { family = "glibc", version = "2.31" }
cuda = "11.8"

[tool.pixi.pypi-dependencies]
lightglue-glomap = { path = ".", editable = true }

[tool.pixi.dependencies]
python = "3.11.*"
pytorch = { version = "2.3.1", channel = "pytorch" }
torchvision = { version = "0.18.1", channel = "pytorch" }
cuda = { version = "*", channel = "nvidia/label/cuda-11.8.0" }
pytorch-cuda = { version = "11.8.*", channel = "pytorch" }
glomap = ">=1.0.0,<2"
hloc = ">=1.4,<2"
colmap = ">=3.8,<4"
icecream = ">=2.1.3,<3"
rich = ">=13.8.1,<14"
appdirs = ">=1.4.4,<2"
tyro = ">=0.8.10,<0.9"
gradio = ">=4.44.0,<5"

[tool.pixi.tasks]
